### ISSUE TITLE
Rules on when preprocessing of anatomical files is run are not clear 

### ISSUE THREAD

**Issue by jAchtzehn** [netstim/leaddbs#696]
Lead-dbs will normally preprocess the anatomical pre-op images which includes cropping, bias-field correction, reslicing to .7 mm isotropic resolution and precoregistration. However, this is only done if neither `.pp` nor `ea_normmethod_applied.mat` are inside the patient's folder. 

This can lead to unwanted and opaque behavior, e.g. when someone uses the same patient folder but manually deletes all files in order to re-run lead-dbs with 'fresh' files. In those cases, .pp is not deleted (unless user has hidden files enabled) and the preprocessing of anatomical files will not be run. 

See [this line](https://github.com/netstim/leaddbs/blob/d2e0029317a9c0d88f5f821320470519ab486a31/ea_autocoord.m#L87) for reference.

My suggestion: make the process more transparent for the user. Some suggestions for a solution:

1. Change line 87 to an OR, so preprocessing is run when `ea_normmethod_applied.mat` is not present
2. Detect if .pp is present, but nothing else and prompt the user `Do you want to rerun preprocessing of anatomical images`

**Comment by andreashorn** [comment]
Hi friends, this is a good point and it's weird behavior with historical origins that we simply never revised.
However, my impression would be that this will be fixed by the BIDS migration, anyways, no?
If we need a quick fix for the classical branch, also: How about instead of .pp (a hidden file) simply write out a small flag file that is not hidden, instead (e.g. "ea_precoreg_complete.mat")? This will be much clearer. Writing out a hidden file was a bad choice to begin with (and goes on meine Kappe of course but I was young and needed the leads).
