### ISSUE TITLE
DioDe GUI manual refinement buttons stop working inconsistently

### ISSUE THREAD

**Issue by jAchtzehn** [netstim/leaddbs#749]
Hello!

Bassam and I recently ran into a troublesome issue with DioDe. Seemingly inconsistently, the GUI buttons will stop working, forcing us to close the DioDe and restarting. Sometimes that works, sometimes it doesn't. It is really a strange problem and I cannot find out how to even consistenly reproduce the error. Hence, I made a video to better showcase it. 

It happens on Lead-DBS 1.5 and 1.6, both macOS and Ubuntu 20.04.
https://user-images.githubusercontent.com/17924124/169080349-7401da16-679c-474b-a479-1d0cea773ecc.mp4

I think it has something to do with [these lines](https://github.com/netstim/leaddbs/blob/d3b55fd5471663a62abae6576339956f5b1280ff/ea_diode_manual.m#L846), where MATLAB just gets stuck in some cases. 

@Till-Dembek any ideas? Can you reproduce this error on your end?

**Comment by andreashorn** [comment]
I agree and had been debugging it myself a bit as well. I think it boils down to a Matlab bug but the use of uiwait and uiresume is not optimal in general I think. I fear refactoring diode is some work but would be worth it.
I’d also give the user a bit more control eg which solution to choose. Finally it’s very hidden at the moment, we should make the process more easy to detect if users have a directional electrode selected?

**Comment by Till-Dembek** [comment]
So I never had these problems on Windows so it seems to ne a Matlab/Unix Problem with uiresume. If anybody has a better concept feel free to change. But transferring DiODe to sth. like AppDesigner would of course be some work which I will not be able to do at the Moment because of hospital stuff. I am against offering the user more choice within the automatic workflow because the automatic worklfow is what is validated and anything else is not (and also because of DAU).

A more prominent button for directional leads would be nice, but where to pur it? I also added a completly manual mode with a new button. Anybody used this yet?
