### ISSUE TITLE
BUG in lead import selecting input / output folders

### ISSUE THREAD

**Issue by andreashorn** [netstim/leaddbs#792]
I currently am not able to load an input or output folder for lead import. No clue why. The path did contain spaces – is that the reason? If so, the user should be informed?

Also please use uigetdir to select the folders.

<img width="1307" alt="Screen Shot 2022-08-10 at 8 08 43 PM" src="https://user-images.githubusercontent.com/1291036/184043768-d9b1f322-69ef-4b6d-a8af-a8850b61979d.png">

**Comment by nrajamani3** [comment]
Sorry, but I could not reproduce this error. My best bet is that selected directory was still remembering an old selection despite changing to a new path (and the old one might have errored out). It cannot be because of spaces since that will only provide a warning. Maybe we can try with the new commits.
