### ISSUE TITLE
Legacy2BIDS import

### ISSUE THREAD

**Issue by Kinway25** [netstim/leaddbs#975]
![Selection_1287](https://user-images.githubusercontent.com/35195806/227735687-4c938123-deb6-404d-a89f-47231295d635.png)

**Comment by Kinway25** [comment]
I could resolve the issue after converting .h5 transformations

**Comment by Kinway25** [comment]
So let's add ea_h5toniigz as a part of legacy2BIDS routine

**Comment by Kinway25** [comment]
Actually, the problem still occurs, so not a real fix

**Comment by nrajamani3** [comment]
Should be fixed with current commit - please check & close if it works. Also add ea_h5toniigz in the routine.

**Comment by ningfei** [comment]
Does `ea_h5toniigz` also handle the reference?

**Comment by nrajamani3** [comment]
In legacy2bids it does not but the function itself takes an input file (any input file) in h5 format and converts it to .nii.gz using ANTs.
Also, in my opinion ea_h5toniigz is not releated to this error. That error was because of falsely representing a modality as `tra`  instead of `ax` - should be fixed now.
